baseURL = "https://tsosi-org.github.io"
DefaultContentLanguage = "en"
title = "TSOSI"
subtitle = "Transparency to Sustain Open Science Infrastructure"
# Using theme as git submodule 
theme = "beautifulhugo"

[markup]
  [markup.highlight]
    style = "catppuccin-mocha"
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This enables us to write HTML directly in the markdown files.
      unsafe = true


[Params]
  selfHosted = true
  subtitle = "Transparency to Sustain Open Science Infrastructure"
  homeTitle = "TSOSI"
  mainSections = ["post"]
#   logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = false
  comments = false
  readingTime = true
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false
  hideAuthor = false

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Contact TSOI"
  website = "tsosi.org"
  email = "contact@tsosi.org"

# [[menu.main]]
#   identifier = "about"
#   name = "About"
#   weight = 4

# [[menu.main]]
#   parent = "about"
#   name = "Contact"
#   url = "page/contact"
#   weight = 2

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

# [[menu.main]]
#   name = "Blog"
#   url = "/blog/"
#   weight = 2

[[menu.main]]
  name = "FAQ"
  url = "page/faq"
  weight = 2

[[menu.main]]
  name = "About"
  url = "page/about"
  weight = 3

# [[menu.main]]
#   name = "Tags"
#   url = "tags"
#   weight = 3

# Activate if you want a presentation tab in the nav bar.
# [[menu.main]]
#   name = "Presentations"
#   url= "presentation"
#   weight = 2

[permalinks]
  [permalinks.page]
    post = "/blog/:filename"
  [permalinks.section]
    post = "/blog/"

[caches]
  [caches.images]
    dir = ":cacheDir/images"