baseURL = "https://blog.tsosi.org"
DefaultContentLanguage = "en"
title = "TSOSI"
subtitle = "Transparency to Sustain Open Science Infrastructure"
# Using theme as git submodule 
theme = "beautifulhugo"

[markup]
  [markup.highlight]
    style = "catppuccin-mocha"
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This enables us to write HTML directly in the markdown files.
      unsafe = true


[Params]
  selfHosted = true
  homeTitle = "TSOSI - blog"
  # subtitle = "Transparency to Sustain Open Science Infrastructure"
  mainSections = ["post"]
  logo = "img/logo_open_graph.png"
#   logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = false
  comments = false
  readingTime = true
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false
  hideAuthor = false

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Contact TSOI"
  website = "tsosi.org"
  email = "contact@tsosi.org"

[[menu.main]]
  identifier = "app"
  url = "https://tsosi.org/"
  name = "App"
  weight = 1

[[menu.main]]
  name = "FAQ"
  url = "https://tsosi.org/pages/faq/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "https://tsosi.org/pages/about/"
  weight = 3

# [permalinks]
#   [permalinks.page]
#     post = "/blog/:filename"
#   [permalinks.section]
#     post = "/blog/"

[caches]
  [caches.images]
    dir = ":cacheDir/images"