name: Deploy redirects to pages

on:
  # push:
  #   branches:
  #     - master

  workflow_dispatch:

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: redirects/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4